[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Make sure admin path works with SPA
[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200

# Ensure Netlify Identity service works
[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"