backend:
  name: git-gateway
  branch: main
  repo: garyp6890/RevreignNew
  site_domain: https://bodyblow.io

media_folder: "public/images"
public_folder: "/images"

# Enable editorial workflow globally
publish_mode: editorial_workflow

collections:
  # ------------------------------------------------------------
  # 1) Site Settings (src/data/settings.json)
  # ------------------------------------------------------------
  - name: "settings"
    label: "Site Settings"
    files:
      - label: "General Settings"
        name: "settings"
        file: "src/data/settings.json"
        extension: "json"
        format: "json"
        fields:
          - label: "Favicon"
            name: "favicon"
            widget: "image"
          - label: "LLM.txt"
            name: "llmTxt"
            widget: "text"
            hint: "Contents of /llm.txt"
          - label: "LLMS.txt"
            name: "llmsTxt"
            widget: "text"
            hint: "Markdown manifest for /llms.txt"

  # ------------------------------------------------------------
  # 2) Homepage (src/data/home.json)
  # ------------------------------------------------------------
  - name: "home"
    label: "Homepage"
    files:
      - label: "Homepage Content"
        name: "home"
        file: "src/data/home.json"
        extension: "json"
        format: "json"
        fields:
          - { label: "Title", name: "title", widget: "string", default: "Homepage" }
          - { label: "Slug",  name: "slug",  widget: "string", default: "home" }
          - { label: "Enable Homepage", name: "enabled", widget: "boolean", default: true }
          - label: "Hero Section"
            name: "hero"
            widget: "object"
            fields:
              - { label: "Enable Hero", name: "enabled", widget: "boolean", default: true }
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Subtitle", name: "subtitle", widget: "string" }
              - { label: "Description", name: "description", widget: "text" }
              - { label: "Background Image", name: "backgroundImage", widget: "image" }
              - { label: "Primary CTA Text", name: "cta1Text", widget: "string" }
              - { label: "Secondary CTA Text", name: "cta2Text", widget: "string" }
          - label: "About Section"
            name: "about"
            widget: "object"
            fields:
              - { label: "Enable About", name: "enabled", widget: "boolean", default: true }
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Description", name: "description", widget: "text" }
              - { label: "Image", name: "image", widget: "image" }
              - { label: "Image Alt Text", name: "altText", widget: "string" }
              - { label: "Show Social Stats", name: "showSocialStats", widget: "boolean", default: true }
          - label: "Featured Merchandise"
            name: "featuredMerch"
            widget: "object"
            fields:
              - { label: "Enable Merchandise", name: "enabled", widget: "boolean", default: true }
              - { label: "Section Title", name: "title", widget: "string" }
              - { label: "Section Description", name: "description", widget: "text" }
              - label: "Items"
                name: "items"
                widget: "list"
                fields:
                  - { label: "Image 1 URL", name: "image1", widget: "image" }
                  - { label: "Image 2 URL", name: "image2", widget: "image" }
                  - { label: "Title", name: "title", widget: "string" }
                  - { label: "Description", name: "description", widget: "text" }
                  - { label: "Buy Link", name: "buyLink", widget: "string" }
                  - { label: "CTA Text", name: "ctaText", widget: "string", default: "Buy Now" }
          - label: "Partnership Section"
            name: "partnerships"
            widget: "object"
            fields:
              - { label: "Enable Partnerships", name: "enabled", widget: "boolean", default: true }
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Description", name: "description", widget: "text" }
              - { label: "Image", name: "image", widget: "image" }
              - { label: "Image Alt Text", name: "altText", widget: "string" }
              - label: "Stats Bullets"
                name: "stats"
                widget: "list"
                fields:
                  - { label: "Stat Text", name: "text", widget: "string" }
              - { label: "CTA Text", name: "ctaText", widget: "string" }
          - label: "Storefronts Section"
            name: "storefronts"
            widget: "object"
            fields:
              - { label: "Enable Storefronts", name: "enabled", widget: "boolean", default: true }
              - { label: "Section Title", name: "title", widget: "string" }
              - { label: "Section Description", name: "description", widget: "text" }
              - label: "Items"
                name: "items"
                widget: "list"
                fields:
                  - { label: "Card Label", name: "label", widget: "string" }
                  - { label: "Destination URL", name: "linkTo", widget: "string" }
                  - { label: "Card Image", name: "image", widget: "image" }
                  - { label: "Description", name: "description", widget: "text" }
                  - { label: "Link Button Text", name: "linkLabel", widget: "string" }

  # ------------------------------------------------------------
  # 3) Links Page (src/data/links.json)
  # ------------------------------------------------------------
  - name: "links"
    label: "Links Page"
    files:
      - label: "Links Page Content"
        name: "links"
        file: "src/data/links.json"
        extension: "json"
        format: "json"
        fields:
          - { label: "Title", name: "title", widget: "string", default: "Connect With Revreign" }
          - { label: "Slug",  name: "slug",  widget: "string", default: "links" }
          - { label: "Enable Page", name: "enabled", widget: "boolean", default: true }
          - { label: "Page Title",  name: "pageTitle", widget: "string" }
          - { label: "Intro Text",  name: "introText", widget: "text" }
          - label: "Social Links"
            name: "socialLinks"
            widget: "list"
            fields:
              - { label: "Platform",  name: "platform",  widget: "string" }
              - { label: "Username",  name: "username",  widget: "string" }
              - { label: "Followers", name: "followers", widget: "string" }
              - { label: "URL",       name: "url",       widget: "string" }
          - label: "Why Follow Section"
            name: "reasonBlock"
            widget: "object"
            fields:
              - { label: "Enable Why Follow", name: "enabled", widget: "boolean", default: true }
              - { label: "Section Title",     name: "title",   widget: "string" }
              - label: "Paragraphs"
                name: "paragraphs"
                widget: "list"
                fields:
                  - { label: "Text", name: "text", widget: "text" }